# Mathematical and Statistical functions

## Iterating over a 1D and 2D numpy array

Iteration in NumPy arrays allows you to traverse, manipulate, and analyze the elements efficiently. Below, we'll explore different approaches to iterating over 1D and 2D arrays, highlighting their functionality and applications.

In [ ]:
import numpy as np
# Generate a 1D array with values in the range 10 to 39
arr1d = np.random.randint(10, 40, size=(10,))
print("Numpy Array: \n", arr1d)
print("Shape: ", arr1d.shape)
# Loop over each element in the array
for item in arr1d:
    print(item, end=" ")

Numpy Array: 
 [21 11 19 39 18 28 20 16 14 37]
Shape:  (10,)
21 11 19 39 18 28 20 16 14 37 

In [ ]:
# Iterating Over a 2D Array - Row-wise Iteration
# Generate a 5×10 2D array
arr2d = np.random.randint(10, 40, size=(5, 10))
print("Numpy Array: \n", arr2d)
print("Shape: ", arr2d.shape)

# Loop over rows in the 2D array
for row in arr2d:
    print(row, end = '\n\n')

Numpy Array: 
 [[34 24 22 14 36 27 33 34 37 15]
 [36 34 24 13 25 39 23 28 18 11]
 [38 11 15 20 38 27 22 10 34 28]
 [21 34 36 25 27 30 32 33 10 22]
 [20 18 34 28 25 11 22 27 29 26]]
Shape:  (5, 10)
[34 24 22 14 36 27 33 34 37 15]

[36 34 24 13 25 39 23 28 18 11]

[38 11 15 20 38 27 22 10 34 28]

[21 34 36 25 27 30 32 33 10 22]

[20 18 34 28 25 11 22 27 29 26]



In [ ]:
# Loop over elements in the 2D array
for row in arr2d:
  for ele in row:
    print(ele, end = ' ')

34 24 22 14 36 27 33 34 37 15 36 34 24 13 25 39 23 28 18 11 38 11 15 20 38 27 22 10 34 28 21 34 36 25 27 30 32 33 10 22 20 18 34 28 25 11 22 27 29 26 

In [ ]:
# Element-wise Iteration
# Loop over each element using ravel (faster, returns a view)
for item in arr2d.ravel():
    print(item, end=" ")

34 24 22 14 36 27 33 34 37 15 36 34 24 13 25 39 23 28 18 11 38 11 15 20 38 27 22 10 34 28 21 34 36 25 27 30 32 33 10 22 20 18 34 28 25 11 22 27 29 26 

## Iteration using np.nditer()

The nditer() function provides advanced iteration with element-wise access and modification capabilities.
* Performance:
> * nditer() is highly efficient for complex iteration and in-place modification.
* Flexibility:
> * Simple loops are intuitive for basic use cases.
> * Advanced iterations with nditer() are ideal for high-performance tasks requiring control.


In [ ]:
# Generate a 1D array with values in the range 10 to 39
arr1d = np.random.randint(10, 40, size=(10,))
print("Numpy Array: \n", arr1d)
print("Shape: ", arr1d.shape)

Numpy Array: 
 [17 11 36 26 36 24 26 30 21 37]
Shape:  (10,)


In [ ]:
# Element-wise iteration using nditer
for item in np.nditer(arr1d):
    print(item, end=' ')

17 11 36 26 36 24 26 30 21 37 

In [ ]:
for item in np.nditer(arr2d):
    print(item, end=' ')

34 24 22 14 36 27 33 34 37 15 36 34 24 13 25 39 23 28 18 11 38 11 15 20 38 27 22 10 34 28 21 34 36 25 27 30 32 33 10 22 20 18 34 28 25 11 22 27 29 26 

## Python Operators on Numpy Array
NumPy supports element-wise operations on arrays using Python's arithmetic operators. These operations automatically apply to each element of the arrays involved, allowing for concise and efficient mathematical computations.

###  Universal Functions: Fast Element-Wise Array Functions
* **Universal functions are the way NumPy allows for vectorization, which promotes clean, efficient and easy-to-maintain code.**
* A universal function, or `ufunc`, is a function that performs element-wise operations on data in ndarrays.
* You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.
> * Many `ufuncs` are simple element-wise transformations like `numpy.sqrt` or `numpy.exp`.
> * Others, such as `numpy.add` or `numpy.maximum`, take two arrays (thus, binary `ufuncs`) and return a single array as the result.

In [ ]:
lst1 = [1, 2, 3, 4]
lst2 = [5, 6, 7, 8]

lst1 + lst2

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
lst1 * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
lst1 * lst2

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
[i+j for i,j in zip(lst1, lst2)]

[6, 8, 10, 12]

In [ ]:
# Define two arrays
data = np.array([1, 2])  # Array with integers
ones = np.ones(2, dtype=int)  # Array of ones with the same shape
# Element-wise addition
result = data + ones
print("Addition Result: ", result)

Addition Result:  [2 3]


In [ ]:
# Element-wise subtraction
result = data - ones
print("Subtraction Result: ", result)

Subtraction Result:  [0 1]


In [ ]:
# Element-wise multiplication
result = data * data
print("Multiplication Result: ", result)

Multiplication Result:  [1 4]


In [ ]:
# Element-wise division
result = data / data
print("Division Result: ", result)

Division Result:  [1. 1.]


In [ ]:
# Exponentiation (**)
data = np.array([2, 3, 4])
result = data ** 2
print("Exponentiation Result: ", result)

Exponentiation Result:  [ 4  9 16]


In [ ]:
# Modulus (%)
data = np.array([10, 15, 20])
result = data % 6
print("Modulus Result: ", result)

Modulus Result:  [4 3 2]


In [ ]:
# Floor Division (//)
data = np.array([10, 15, 20])
result = data // 6
print("Floor Division Result: ", result)

Floor Division Result:  [1 2 3]


## NumPy Mathematical Operations
NumPy provides a wide range of mathematical functions that can be applied element-wise to arrays. These operations include functions for basic arithmetic, trigonometry, exponents, and matrix multiplication.

###  Basic Element-Wise Mathematical Functions
These operations apply mathematical functions element-wise to each array element.

In [ ]:
# Applying mathematical operations on scalars
print("Square Root: ", np.sqrt(4))  # Square root of scalar 4
print("Exponent: ", np.exp(1))     # Exponent of scalar 1
print("Trigonometric Sin: ", np.sin(0))  # Sine of scalar 0
print("Trigonometric Cos: ", np.cos(0))  # Cosine of scalar 0

Square Root:  2.0
Exponent:  2.718281828459045
Trigonometric Sin:  0.0
Trigonometric Cos:  1.0


In [ ]:
arr = np.array([1, 2, 3, 4])
print("Square Root: ", np.sqrt(arr))  # Element-wise square root
print("Exponent: ", np.exp(arr))     # Element-wise exponent
print("Trigonometric Sin: ", np.sin(arr))  # Element-wise sine
print("Trigonometric Cos: ", np.cos(arr))  # Element-wise cosine

Square Root:  [1.         1.41421356 1.73205081 2.        ]
Exponent:  [ 2.71828183  7.3890561  20.08553692 54.59815003]
Trigonometric Sin:  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Trigonometric Cos:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


### Basic Element-Wise Arithmetic Operations
NumPy allows element-wise addition, subtraction, multiplication, and division. These operations are applied element by element across arrays of the same shape.


In [ ]:
# Define two arrays
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
# Perform element-wise arithmetic operations
print("Elementwise Addition: \n", np.add(x, y))        # Addition
print("Elementwise Subtraction: \n", np.subtract(x, y))# Subtraction
print("Elementwise Multiplication: \n", np.multiply(x, y))  # Multiplication
print("Elementwise Division: \n", np.divide(x, y))     # Division

Elementwise Addition: 
 [[ 6  8]
 [10 12]]
Elementwise Subtraction: 
 [[-4 -4]
 [-4 -4]]
Elementwise Multiplication: 
 [[ 5 12]
 [21 32]]
Elementwise Division: 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


### NumPy Matrix Multiplication
Matrix multiplication is a common operation in linear algebra and machine learning. NumPy provides multiple ways to perform matrix multiplication.


In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# Matrix multiplication methods
print("Matrix Multiplication (Way-1): \n", np.matmul(x, y))  # Using np.matmul()
print("Matrix Multiplication (Way-2): \n", np.dot(x, y))     # Using np.dot()
print("Matrix Multiplication (Way-3): \n", x @ y)           # Using the @ operator

Matrix Multiplication (Way-1): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-2): 
 [[19 22]
 [43 50]]
Matrix Multiplication (Way-3): 
 [[19 22]
 [43 50]]


## Numpy Statistical functions
NumPy provides powerful tools for statistical analysis, allowing you to calculate measures like minimum, maximum, mean, median, variance, standard deviation, and correlation. These operations can be performed on an entire array or along a specified axis.

### Maximum and Minimum Values
NumPy provides min and max methods (or their function equivalents np.min and np.max) to find the minimum and maximum values in arrays. These methods can also operate along specific axes using the axis argument.


In [ ]:
# Create a 2D array
a = np.array([[3, 0, -1, 1], [2, -1, -2, 4], [1, 7, 0, 4]])
a

array([[ 3,  0, -1,  1],
       [ 2, -1, -2,  4],
       [ 1,  7,  0,  4]])

In [ ]:
# Minimum and maximum values
print("Minimum Value: ", np.min(a))
print("Maximum Value: ", np.max(a))

Minimum Value:  -2
Maximum Value:  7


In [ ]:
# Minimum values along columns (axis=0)
print("Minimum Along Columns: ", np.min(a, axis=0))

Minimum Along Columns:  [ 1 -1 -2  1]


In [ ]:
# Maximum values along rows (axis=1)
print("Maximum Along Rows: ", np.max(a, axis=1))

Maximum Along Rows:  [3 4 7]


### Indices of Maximum and Minimum Values
To find the index of the minimum or maximum value in an array, use argmin or argmax. By default, these functions return the index in the flattened array. To operate along axes, use the axis argument.


In [ ]:
# Index of minimum and maximum values
print("Index of Minimum Value: ", np.argmin(a))
print("Index of Maximum Value: ", np.argmax(a))

Index of Minimum Value:  6
Index of Maximum Value:  9


In [ ]:
# Indices along specific axes
print("Index of Max Along Columns: ", np.argmax(a, axis=0))
print("Index of Min Along Rows: ", np.argmin(a, axis=1))

Index of Max Along Columns:  [0 2 2 1]
Index of Min Along Rows:  [2 2 2]


### Handling NaN Values
When arrays contain NaN values, the functions np.nanmin and np.nanmax can be used to ignore them.

In [ ]:
# To create NAN
frac = np.array(0)/np.array(0)
print(frac)

nan


<ipython-input-67-4866a59107a0>:2: RuntimeWarning: invalid value encountered in divide
  frac = np.array(0)/np.array(0)


In [ ]:
num = np.array(3)/np.array(0)
print(num)

inf


<ipython-input-68-437d5150a5e8>:1: RuntimeWarning: divide by zero encountered in divide
  num = np.array(3)/np.array(0)


In [ ]:
print(np.pi)

3.141592653589793


In [ ]:
print(np.nan)
type(np.nan)

nan


float

In [ ]:
1 + np.nan

nan

In [ ]:
1 - np.nan

nan

In [ ]:
1 * np.nan

nan

In [ ]:
1 / np.nan

nan

In [ ]:
np.nan**2

nan

In [ ]:
1 > np.nan

False

In [ ]:
1 < np.nan

False

In [ ]:
1 == np.nan

False

In [ ]:
# Create an array with NaN values
b = np.array([1, np.nan, 3, np.nan, 5])
b

array([ 1., nan,  3., nan,  5.])

In [ ]:
np.argmax(b), np.argmin(b)

(np.int64(1), np.int64(1))

In [ ]:
# Ignore NaNs while finding min and max
print("Min Ignoring NaNs: ", np.nanmin(b))
print("Max Ignoring NaNs: ", np.nanmax(b))

Min Ignoring NaNs:  1.0
Max Ignoring NaNs:  5.0


### Comparing Arrays
Functions like np.minimum and np.maximum compare two arrays element-wise, propagating NaNs, while np.fmin and np.fmax ignore NaNs.


In [ ]:
c1

array([ 1, -5,  6,  2])

In [ ]:
c2

array([ 0., nan, -1., -1.])

In [ ]:
# Element-wise comparison
c1 = np.array([1, -5, 6, 2])
c2 = np.array([0, np.nan, -1, -1])
print("Ignoring NaNs (fmin): ", np.fmin(c1, c2))
print("Propagating NaNs (minimum): ", np.minimum(c1, c2))

Ignoring NaNs (fmin):  [ 0. -5. -1. -1.]
Propagating NaNs (minimum):  [ 0. nan -1. -1.]


In [ ]:
print("Ignoring NaNs (fmin): ", np.fmax(c1, c2))
print("Propagating NaNs (minimum): ", np.maximum(c1, c2))

Ignoring NaNs (fmin):  [ 1. -5.  6.  2.]
Propagating NaNs (minimum):  [ 1. nan  6.  2.]


### Averages, Variances, and Correlations
The mean is the arithmetic average of the elements in the array. Missing values (NaN) can be ignored using np.nanmean.

In [ ]:
# Basic Mean Calculation
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Mean: ", np.mean(matrix))
print("Mean Along Columns: ", np.mean(matrix, axis=0))
print("Mean Along Rows: ", np.mean(matrix, axis=1))

Mean:  3.5
Mean Along Columns:  [2.5 3.5 4.5]
Mean Along Rows:  [2. 5.]


In [ ]:
# Basic Median Calculation
print("Median: ", np.median(matrix))
print("Median Along Columns: ", np.median(matrix, axis=0))
print("Median Along Rows: ", np.median(matrix, axis=1))

Median:  3.5
Median Along Columns:  [2.5 3.5 4.5]
Median Along Rows:  [2. 5.]


In [ ]:
# Basic Variance and Standard Deviation
print("Variance: ", np.var(matrix))
print("Standard Deviation: ", np.std(matrix))

Variance:  2.9166666666666665
Standard Deviation:  1.707825127659933


In [ ]:
# Handling NaN values
matrix_nan = np.array([[1, np.nan, 3], [4, 5, np.nan]])
print("Mean Ignoring NaNs: ", np.nanmean(matrix_nan))
print("Mean Along Columns Ignoring NaNs: ", np.nanmean(matrix_nan, axis=0))
print("Mean Along Rows Ignoring NaNs: ", np.nanmean(matrix_nan, axis=1))

Mean Ignoring NaNs:  3.25
Mean Along Columns Ignoring NaNs:  [2.5 5.  3. ]
Mean Along Rows Ignoring NaNs:  [2.  4.5]


In [ ]:
# Handling NaN values
print("Median Ignoring NaNs: ", np.nanmedian(matrix_nan))
print("Median Along Columns Ignoring NaNs: ", np.nanmedian(matrix_nan, axis=0))
print("Median Along Rows Ignoring NaNs: ", np.nanmedian(matrix_nan, axis=1))

Median Ignoring NaNs:  3.5
Median Along Columns Ignoring NaNs:  [2.5 5.  3. ]
Median Along Rows Ignoring NaNs:  [2.  4.5]


In [ ]:
# Handling NaN values
print("Variance Ignoring NaNs: ", np.nanvar(matrix_nan))
print("Standard Deviation Ignoring NaNs: ", np.nanstd(matrix_nan))

Variance Ignoring NaNs:  2.1875
Standard Deviation Ignoring NaNs:  1.479019945774904


In [ ]:
# Weighted Average
x = np.array([1.0, 4.0, 9.0, 16.0])
weights = [0.0, 3.0, 1.0, 0.0]

# Weighted Average
print("Weighted Average: ", np.average(x, weights=weights))

Weighted Average:  5.25


In [ ]:
# Covariance
X = np.array([[0.1, 0.3, 0.4], [3.2, 2.4, 2.4]])
print("Covariance Matrix: \n", np.cov(X))

Covariance Matrix: 
 [[ 0.02333333 -0.06666667]
 [-0.06666667  0.21333333]]


In [ ]:
# Correlation
x = np.array([1.0, 2.0, np.nan, 4.0, 5.0])
y = np.array([0.08, 0.31, 0.41, np.nan, 0.62])

print("Correlation Coefficient (Ignoring NaNs): \n", np.corrcoef(x, y))

Correlation Coefficient (Ignoring NaNs): 
 [[nan nan]
 [nan nan]]


In [ ]:
# Correlation
x = np.array([1.0, 2.0, np.nan, 4.0, 5.0])
y = np.array([0.08, 0.31, 0.41, np.nan, 0.62])

# Replace NaN values with 0 for computation
x_clean = np.nan_to_num(x)
y_clean = np.nan_to_num(y)

print("Correlation Coefficient (Ignoring NaNs): \n", np.corrcoef(x_clean, y_clean))

Correlation Coefficient (Ignoring NaNs): 
 [[1.         0.18839223]
 [0.18839223 1.        ]]


### Summation and Min/Max Per Axis
NumPy's ndarray.sum() method allows you to calculate the sum of array elements along a specified axis. Understanding how axis=0 and axis=1 work is crucial for effective data manipulation in NumPy.


In [ ]:
matrix = np.array([[0, 1], [2, 3]])
matrix

array([[0, 1],
       [2, 3]])

In [ ]:
np.sum(matrix), np.sum(matrix, 0), np.sum(matrix, axis=0)

(np.int64(6), array([2, 4]), array([2, 4]))

In [ ]:
np.sum(matrix), np.sum(matrix, 1), np.sum(matrix, axis=1)

(np.int64(6), array([1, 5]), array([1, 5]))

In [ ]:
print("Column-wise Sum: ", np.sum(matrix, axis=0))
print("Row-wise Sum: ", np.sum(matrix, axis=1))

Column-wise Sum:  [2 4]
Row-wise Sum:  [1 5]


In [ ]:
matrix_nan = np.array([[np.nan, 2, 3], [4, 5, np.nan]])
matrix_nan

array([[nan,  2.,  3.],
       [ 4.,  5., nan]])

In [ ]:
print("Sum: ", np.sum(matrix_nan))

Sum:  nan


In [ ]:
print("Sum: ", np.nansum(matrix_nan))

Sum:  14.0


In [ ]:
print("Minimum: ", np.min(matrix))
print("Column-wise Minimum: ", np.min(matrix, axis=0))
print("Row-wise Minimum: ", np.min(matrix, axis=1))

Minimum:  0
Column-wise Minimum:  [0 1]
Row-wise Minimum:  [0 2]


In [ ]:
matrix[0, 0] = np.nan

ValueError: cannot convert float NaN to integer

In [ ]:
matrix = matrix.astype('float')
matrix[0, 0] = np.nan
matrix

array([[nan,  1.],
       [ 2.,  3.]])

In [ ]:
matrix[1, 1] = np.nan
matrix

array([[nan,  1.],
       [ 2., nan]])

In [ ]:
print("Maximum", np.max(matrix))
print("Minimum", np.min(matrix))

Maximum nan
Minimum nan


In [ ]:
print("Maximum Ignoring NaNs: ", np.nanmax(matrix))
print("Minimum Ignoring NaNs: ", np.nanmin(matrix))

Maximum Ignoring NaNs:  2.0
Minimum Ignoring NaNs:  1.0
